name: Deploy to Development

on:
  push:
    branches:
      - development

env:
  # Setup AWS credentials
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy-development:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Switch to Yarn v3
        run: corepack enable && yarn -v

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn run build

      - name: Deploy to development environment
        run: yarn deploy:dev
