name: Playwright E2E Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Switch to Yarn v3
        run: corepack enable && yarn -v

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright Browsers
        run: yarn run test:e2e:install

      - name: Run Playwright tests
        run: yarn run test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # - name: Install Playwright Browsers
      #   run: yarn run test:e2e:install

      # - name: Run Playwright tests
      #   run: yarn playwright test
      #   # run: yarn run test:e2e

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 1
