name: Remove PR Deployment

on:
  pull_request:
    types: [closed]

env:
  # Setup AWS credentials
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  remove-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Switch to Yarn v3
        run: corepack enable && yarn -v

      - name: Install dependencies
        run: yarn install --immutable

      - name: Remove deployment
        run: |
          if ${{ github.event.pull_request.merged == true || github.event.pull_request.state == 'closed' }}; then
            # Remove the deployment using sst with the PR number as the stage
            npx sst remove --stage pr-${{ github.event.pull_request.number }}
          fi
