name: Remove PR Deployment

on:
  pull_request:
    types: [closed]

jobs:
  remove-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove deployment
        run: |
          if ${{ github.event.pull_request.merged == true || github.event.pull_request.state == 'closed' }}; then
            # Replace <YOUR_AWS_CREDENTIALS_HERE> and <YOUR_AWS_SECRET_HERE> with your AWS credentials
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

            # Remove the deployment using sst with the PR number as the stage
            sst remove --stage pr-${{ github.event.pull_request.number }}
          fi
